[package]
name = "roblox/promise"
description = "An implementation of Promise similar to Promise/A+."
version = "3.5.1"
license = "MIT"
authors = ["evaera"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/roblox-lua-promise"

[dependencies]
